### ISSUE TITLE
Please add user system, database and admin panel

### ISSUE THREAD

**Issue by Janikneo** [markhillard/Editor#13]
Please add user system, database and admin panel

**Comment by markhillard** [comment]
@Janikneo, this project is only meant to be a front-end tool, so there will be no back-end database or admin panel.

**Comment by Janikneo** [comment]
Are there any analogues with this fuctional? With admin panel and database?

**Comment by markhillard** [comment]
Sorry, I haven't built any server-side structure for this to enable connection to a database. It's simply hosted on GitHub Pages and it's all front-end HTML, CSS and JS.
