### ISSUE TITLE
Console support?

### ISSUE THREAD

**Issue by zilveer** [markhillard/Editor#16]
**Is your feature request related to a problem? Please describe.**
I would like to debug the errors and check the outputs while I am coding.

**Describe the solution you'd like**
A panel where it is possible for the user to show/hide Console outputs.

**Describe alternatives you've considered**
As long as I get the Console outputs I am enjoyed :)

**Additional context**
Developer Console output so I can see `console.log('This is my output');` in a panel or view somewhere .

And last but not least thanks for a such a great standalone live code editor!
Best regards Zilveer

**Comment by ldarren** [comment]
@zilveer is the `console` comes with browser not good enough for your needs?

**Comment by zilveer** [comment]
@ldarren thanks for the quick reply.
I think that an integrated `console` for the app would actually make it easier for the development , it could anyway be an option.
Often I am mobile and can only use the phone for testing and coding and then the console would do a really good job .

Best regards Zilveer

**Comment by markhillard** [comment]
@zilveer, thanks for the feature request. I can see how this would be useful, especially on mobile. I've used the console feature in CodePen before, so I'm assuming that's what you're talking about.

I'm not quite sure what the best and most useful way is to implement this, but if I come up with something I'll keep you updated here.

**Comment by zilveer** [comment]
@markhillard yeah you got it correct about using it while using the mobile.

There is https://jsconsole.com/ so perhaps that plugin could be used?

Regards Zilveer

**Comment by zilveer** [comment]
Any update regarding the console support ?

**Comment by markhillard** [comment]
@zilveer - for now I don't see myself adding this type of functionality, since there are already great built-in consoles in browsers such as Firefox and Chrome. These have worked great for me and will log everything you run in Editor. The preview window `<iframe>` is in "sandbox" mode, which allows scripts to run, and therefore your browser console will pick them up.
