### ISSUE TITLE
Preview isn't the same on a Codepen example

### ISSUE THREAD

**Issue by zilveer** [markhillard/Editor#17]
**Describe the bug**
The codepen example found at [https://codepen.io/mjgartendev/pen/zQOLqW](https://codepen.io/mjgartendev/pen/zQOLqW) doesn't look and behave as it should in your Editor, and I have tried to make it work on your editor but it just doesn't work and I wonder why ?

**To Reproduce**
1. Go to '...' https://codepen.io/mjgartendev/pen/zQOLqW
2. Copy HTML /CSS /JS code to the editor 
3. Copy also the HTML meta and the rest of the code  shown in the pen settings for the HTML part. Paste to the first line in the Editor HTML part
4. See the preview , it doesn't work 

**Expected behavior**
Preview on Codepen and Editor isn't the same.

**Screenshots**
Will add tomorrow

**Desktop (please complete the following information):**
 - OS: win7
 - Browser: Chrome (latest) and FF (latest)?

 - 
**Additional context**
A fix for this or to understand why it doesn't work would be appreciated.

**Comment by zilveer** [comment]
Oh I just saw that it is about compiling `SCSS` to `CSS` and `TypeScript` to `JS`, so it works out of the box on your editor.:)

But perhaps adding support for compiling `SCSS` to `CSS` and `TypeScript` to `JS`, is that possible?

**Comment by markhillard** [comment]
@zilveer, this editor was never meant to have built-in transpilation. I think it could be possible, but to be honest I don't have the time to get into something like this right now. If/when I do, I'll update this issue.
