### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by rudrasoftwarecorporation** [markhillard/Editor#18]
I tested the downloaded file and the preview doesn't work

**Comment by markhillard** [comment]
All the download button does is generate a plain HTML file with all your code from the HTML, CSS, and JS windows. It's really just a way to save your code locally. If the preview doesn't work when opening that file, then I would recommend taking a look at your code again, check to see if there are any errors in your browser console, make sure any paths to JS dependencies are correct, etc.

**Comment by rudrasoftwarecorporation** [comment]
Ok sir

**Comment by rudrasoftwarecorporation** [comment]
Excuse me sir but there's one more problem

**Comment by markhillard** [comment]
@rudrasoftwarecorporation, what's the problem?

**Comment by rudrasoftwarecorporation** [comment]
Sir the html export isn't working also

**Comment by markhillard** [comment]
@rudrasoftwarecorporation, I'm not sure what you mean. Are you still talking about the "Save" button? Simply saying that "something is not working" is not helpful in any way. I don't mind helping you but you will need to provide more details.

- What web browser are you using?
- What operating system are you using?
- Are you on desktop or mobile?
- Are there any error messages you're receiving?
- Can you provide any screenshots?

Better yet, please use the following template in your next response: https://github.com/markhillard/Editor/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md
