### ISSUE TITLE
Feature: Download Option

### ISSUE THREAD

**Issue by ghost** [markhillard/Editor#9]
Awesome project you've got here! 

Would be neat if there were an option to download the code, either in ZIP format with html/css/js files or possibly concat all into a single file... 

No clue how to implement this, so afraid I can't help, but figured I'd run the suggestion by you : ) 

Cheers!

**Comment by markhillard** [comment]
Thanks @rubyframework !! I've been thinking of implementing an "about/help" area in some way, and I like your idea of adding a direct link to download the whole project. I'll let you know when there's some progress on this.

**Comment by markhillard** [comment]
@rubyframework, thank you! This is a great idea. I did some research on how to do this client-side and found [FileSaver.js](https://github.com/eligrey/FileSaver.js). It looks promising and has good browser support.
